# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Determine if vector is constant (or zero length)
#'
#' @param var A numeric vector
#' @keywords internal
const_vect <- function(var) {
    .Call(`_CausalGrid_const_vect`, var)
}

